### ISSUE TITLE
Link to github on itch.io links to "https://github.com/dulvui/pocket-broomall" (missing a b)

### ISSUE THREAD

**Issue by RustoMCSpit** [dulvui/pocket-broomball#13]

**Comment by RustoMCSpit** [comment]
If you want to add your team to the game, send me a mail at info@simondalvai.com
🧹 100+ real-world teams
🌈 20+ different styled balls to collect
📡 Offline game
📺 No ads
💸 No In-App purchases
🕵️‍♀️ No user tracking
🛑 No permissions needed
📖 Open Source on https://github.com/dulvui/pocket-broomall
👨‍💻 Created with Godot Engine 3

**Comment by dulvui** [comment]
Thank you so much! I'm make a lot of typos :sweat_smile: 
I fixed it now

**Comment by RustoMCSpit** [comment]
> Thank you so much! I'm make a lot of typos 😅 I fixed it now

any update on a new release? also what FOSS ide do you recommend?

**Comment by dulvui** [comment]
This weekend I hope, sorry for the delay, but I'm also working on other games.
I use Godot Engine to create my games and VSCodium for all the other stuff. It highly depends what programming language you want to code, but  VSCodium supports a lot of them.
