### ISSUE TITLE
The shop's arrows, lock, and numbers should follow a color scheme

### ISSUE THREAD

**Issue by RustoMCSpit** [dulvui/pocket-broomball#17]
https://colorhunt.co/
or 
https://github.com/dulvui/pocket-broomball/issues/4

each increase in number has a different shade too

**Comment by RustoMCSpit** [comment]
Also should apply to the hall of fame

**Comment by RustoMCSpit** [comment]
> https://colorhunt.co/ or #4
> 
> each increase in number has a different shade too

or material you design

**Comment by dulvui** [comment]
I changed now the shop buttons with `<` and `>` buttons like in my other games and I won't use a color scheme since I would have to implement different themes or custom button styles for single buttons. Godot themes support only one style for buttons.
