### ISSUE TITLE
Have an emoji or flag beside each language

### ISSUE THREAD

**Issue by RustoMCSpit** [dulvui/pocket-broomball#19]

**Comment by dulvui** [comment]
Flags are now visible on the language button and will be available with the next update.
![image](https://github.com/dulvui/pocket-broomball/assets/12729238/3152d585-d6bb-4b1d-b9fd-2dace5341a9c)

**Comment by RustoMCSpit** [comment]
whats the resolution of those images

**Comment by RustoMCSpit** [comment]
https://github.com/dulvui/pocket-broomball/issues/28 how do these mix

**Comment by dulvui** [comment]
the resolution is 250x250 pixels
![image](https://github.com/dulvui/pocket-broomball/assets/12729238/196e879d-3042-43d2-bb0d-254e79f6d81f)
So it looks with transparency 200 of 256. I have to say I like it a lot, might keep it like this.

**Comment by RustoMCSpit** [comment]
> the resolution is 250x250 pixels ![image](https://private-user-images.githubusercontent.com/12729238/287523463-196e879d-3042-43d2-bb0d-254e79f6d81f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3MjM0MDIsIm5iZiI6MTcwMTcyMzEwMiwicGF0aCI6Ii8xMjcyOTIzOC8yODc1MjM0NjMtMTk2ZTg3OWQtMzA0Mi00M2QyLWJiMGQtMjU0ZTc5ZjZkODFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA0VDIwNTE0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQyYTRkMWRmZGFjOTllNDcxYjYyMzlhOTMxYzBiYmM2OGYxNjZkYjBiZGQ0OTUyODkwYzQ3M2I4ZmI4MTM0NzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Vj_Wz0n72IayiPM6I-KrLFIMSICrmpMVqUZlW40F1zM) So it looks with transparency 200 of 256. I have to say I like it a lot, might keep it like this.

can you make milestones btw

**Comment by dulvui** [comment]
No, milestones don't make sense to me, as I told you already in another issue.

**Comment by RustoMCSpit** [comment]
> No, milestones don't make sense to me, as I told you already in another issue.

sorry i forgot

**Comment by dulvui** [comment]
No worries
