### ISSUE TITLE
Replay in Bot vs. Bot enters 2P instead

### ISSUE THREAD

**Issue by Eiim** [dulvui/pocket-broomball#24]
When clicking "Replay" after a Bot v. Bot game, it enters 2P mode instead.

Version 5.0.5, from F-Droid.

**Comment by dulvui** [comment]
Thanks for opening the issue! Now it's fixed and I will publish a new version this weekend.
I will just work on some other issue and then publish an updated with multiple fixes.

**Comment by dulvui** [comment]
Fixed in latest version 5.0.6 available on itch.io, Play Store and App Store.
Update should also come to F-Droid in the next days.
