### ISSUE TITLE
Going to Play ---> 1 Player causes the 'Go back' button to move upwards

### ISSUE THREAD

**Issue by RustoMCSpit** [dulvui/pocket-broomball#25]
Also, clicking the 'Go back' button causes the logo to disappear for a split second

**Comment by dulvui** [comment]
I aligned the buttons in all menus and fixed the icon as well. Now also when you click go back after "1 Player" you actually go back to the play selection instead of the menu.

**Comment by dulvui** [comment]
I generally improved the UI in the latest build and it should also fix this issue.
