### ISSUE TITLE
not every hit should make a noise

### ISSUE THREAD

**Issue by RustoMCSpit** [dulvui/pocket-broomball#3]
when the ball gets spam hit against the wall it sounds ridiculous. also, each hit's volume shpuld be based on velocity of the player hitting it / distance it travelled to hit wall

**Comment by dulvui** [comment]
Thank you for your feedback! This makes sense and I will try to improve the wall hit sounds in the next update. Technically it should be possible making the sound volume dynamic.
I'll keep you updated on this.

**Comment by RustoMCSpit** [comment]
thank you, also id advise making hit sounds have slight differences. i think this can be done with a randomiser and an eq but better if you look into it

**Comment by dulvui** [comment]
Thanks for your tips! I added now a random pitch and the volume is dynamic, depending on the ball speed or the impact force a player has. I will fine tune it a bit and then release a new version on itch.io, so you can test before I release it on the mobile platforms.

**Comment by RustoMCSpit** [comment]
consider having a 'musical mode' which makes the hits only operate within the c major scale (randomly)

**Comment by dulvui** [comment]
The random pitch and a max ball hit sound is now implemented since version 5.0.5
