### ISSUE TITLE
Opponents logo is mirrored, not on its head

### ISSUE THREAD

**Issue by david-hil** [dulvui/pocket-broomball#32]
The opponents team logo is mirrored along the midline, instead of on its head (i.e. point mirrored through the midpoint). Very noticeable, when you turn your screen around.

**Comment by dulvui** [comment]
Thank you for reporting this!

How should it look? This looks fine to me.
![image](https://github.com/dulvui/pocket-broomball/assets/12729238/7390780a-57b7-488a-8c15-52205fea6428)

**Comment by david-hil** [comment]
It looks mostly fine, but if you have "Broomball Neumarkt" at the bottom, the writing is normal, if you flip your phone, the writing of "Vikings" is mirrored

**Comment by dulvui** [comment]
Oooh now I see it. It's fixed now and I'll close the issue asap the new version is online

**Comment by dulvui** [comment]
Fixed with version 5.1.1
