### ISSUE TITLE
First ball appears locked when first opening the shop

### ISSUE THREAD

**Issue by G-B-FutureMartian** [dulvui/pocket-broomball#34]
The ball has a lock on when you open the shop. If you switch to a different ball then it disappears.

**Comment by dulvui** [comment]
Thank you very much for opening the issue! Its fixed now and I will close the issue as soon the next update with the fix is available.
I think this weekend I'll release a new version with the latest bug fixes.

**Comment by dulvui** [comment]
Fixed with version 5.1.1
