### ISSUE TITLE
Second orange ball

### ISSUE THREAD

**Issue by G-B-FutureMartian** [dulvui/pocket-broomball#35]
There are two identical orange balls in the game, but one is free and the other is 50,000 coins.

**Comment by dulvui** [comment]
Thank you for opening the issue!
I used now the black ball that was actually already there, I forgot to use it.

The fix will be available in the next version this weekend probably, do I'll add also new balls, sticks and helmets.

**Comment by dulvui** [comment]
Fixed in version 5.1.3 with 7 new striped balls.
This version will be available soon on all platforms.
