### ISSUE TITLE
Option to choose how much points is needed for victory

### ISSUE THREAD

**Issue by inson1** [dulvui/pocket-broomball#36]
So I could select more/less points like 69 or just 1.

**Comment by dulvui** [comment]
Thank you for your feedback!
I will add a option to modify the points in the play section, but it will not apply to tournaments. There the final score will always remain 5.

**Comment by inson1** [comment]
@dulvui What about the audio for more than 5? Mainly if there is any?
I think 100 could be more than enough

**Comment by dulvui** [comment]
Oh I forgot about the audio of the numbers, if I remember right it goes until 10.
If that is correct I might set the limit to 10 or search for other audios, but I think 10 should be enough.

**Comment by dulvui** [comment]
In version 5.2.0 the victory goals can be changed from 1 to 9 for all game modes except tournaments in the settings.
