### ISSUE TITLE
add support for custom monochrome android 13 icon theming 

### ISSUE THREAD

**Issue by RustoMCSpit** [dulvui/pocket-broomball#4]

**Comment by dulvui** [comment]
Thanks for the hint! I will checkout and see if this is possible with Godot 3, but it seems that by setting an adaptive icon should work.

**Comment by RustoMCSpit** [comment]
https://developer.android.com/develop/ui/views/launch/icon_design_adaptive

**Comment by dulvui** [comment]
Monochrome icons are still not supported by Godot 3, and I don't think it will be supported, since new features are mainly added to Godot 4. Feel free to reopen the issue, if monochrome icons are supported on Godot 3.
