### ISSUE TITLE
buttons should be shaded on click in settings

### ISSUE THREAD

**Issue by RustoMCSpit** [dulvui/pocket-broomball#7]
the font dips for the illusion of a push but the shading remains the same

**Comment by dulvui** [comment]
Thank you for opening the issue! I will improve the button click animation within the next update.
Could you please explain more, what you mean with "font dips"?

**Comment by RustoMCSpit** [comment]
> Thank you for opening the issue! I will improve the button click animation within the next update. Could you please explain more, what you mean with "font dips"?

the text dips on the y axis briefly on button press

**Comment by RustoMCSpit** [comment]
https://colorhunt.co/
or
https://github.com/dulvui/pocket-broomball/issues/4

i suggest looking through these palettes for ideas on a new color scheme for buttons, the play button should be a different color as it is most important

On and Off should also be different, Music off for example

**Comment by RustoMCSpit** [comment]
is this issue completed? if so, please close

**Comment by dulvui** [comment]
I like the buttons how they look now, so closing the issue.
