### ISSUE TITLE
change .wav files to .opus 

### ISSUE THREAD

**Issue by RustoMCSpit** [dulvui/pocket-broomball#8]
game/assets/sounds/music.wav.import
game/assets/sounds/chill-music.wav.import

.wav wastes storage and isnt foss, even if lossless was needed .flac would be better. storing via lossy would be better

**Comment by RustoMCSpit** [comment]
also when the time comes maybe consider moving images to .jxl? it isnt that well adopted yet though

**Comment by dulvui** [comment]
Thanks, I didn't know about opus.
`.jxl` is currently not supported yet by the Godot Engine https://docs.godotengine.org/en/stable/tutorials/assets_pipeline/importing_images.html#supported-image-formats
Also `.opus` is currently not supported https://docs.godotengine.org/en/stable/tutorials/assets_pipeline/importing_audio_samples.html#supported-audio-formats

I'll close the issue and reopen it, once the file formats are supported.

**Comment by RustoMCSpit** [comment]
.


.flac?

**Comment by RustoMCSpit** [comment]
https://github.com/godotengine/godot-proposals/issues/8011

**Comment by RustoMCSpit** [comment]
.ogg vorbis is

**Comment by Calinou** [comment]
> .wav wastes storage and isnt foss

The WAV format specification is public (it's also fairly simple) and there are no known active patents around it. This makes the format easy to use in open source software.

**Comment by RustoMCSpit** [comment]
> > .wav wastes storage and isnt foss
> 
> The WAV format specification is public (it's also fairly simple) and there are no known active patents around it. This makes the format easy to use in open source software.

oh cool didnt know

**Comment by dulvui** [comment]
@RustoMCSpit I changed now all .wav to .ogg after I saw the big file size difference it makes.
Thanks for the hint!

**Comment by RustoMCSpit** [comment]
> @RustoMCSpit I changed now all .wav to .ogg after I saw the big file size difference it makes. Thanks for the hint!

whens the next update coming!!

**Comment by RustoMCSpit** [comment]
> @RustoMCSpit I changed now all .wav to .ogg after I saw the big file size difference it makes. Thanks for the hint!

btw just in case you dont know, .wav is lossless so no quality is lost but .opus is lossy so the quality is slightly worsened. the difference is honestly very minimal though
